version: '3'
services:
  redis-server:
    image: "redis:alpine"
    container_name: "redis-server"
    ports:
      - "6379:6379"
  
  benchmark-app:
    build: .
    container_name: "go-benchmark-app"
    environment:
      - GOMAXPROCS=2
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
    command: ["benchmark-api"]  # Corrected to match the binary name

  caddy:
    image: "caddy:latest"
    container_name: "caddy-server"
    ports:
      - "80:80"
    depends_on:
      - benchmark-app
    command: ["caddy", "reverse-proxy", "--from", ":80", "--to", "benchmark-app:8080"]
